apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xqgp5mlqu-go
  janus-idp.io/tekton: xqgp5mlqu-go
  backstage.io/kubernetes-id: xqgp5mlqu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xqgp5mlqu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
